//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localiztion {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localiztion.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 非法货物数量，当前货物数量应在以下范围： 的本地化字符串。
        /// </summary>
        public static string AddTakeOutRequest_IllegalCount_MSG {
            get {
                return ResourceManager.GetString("AddTakeOutRequest_IllegalCount_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击禁止鼠标拖拽 的本地化字符串。
        /// </summary>
        public static string BT_Arrow {
            get {
                return ResourceManager.GetString("BT_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string BT_Confirm {
            get {
                return ResourceManager.GetString("BT_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击并通过鼠标拖拽(Ctrl) 的本地化字符串。
        /// </summary>
        public static string BT_Hand {
            get {
                return ResourceManager.GetString("BT_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重设 的本地化字符串。
        /// </summary>
        public static string BT_Rest {
            get {
                return ResourceManager.GetString("BT_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string BT_Save {
            get {
                return ResourceManager.GetString("BT_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否确认修改整列为轨道 的本地化字符串。
        /// </summary>
        public static string ConfirmModifyToRail {
            get {
                return ResourceManager.GetString("ConfirmModifyToRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CreateMap_Alert_Cancel {
            get {
                return ResourceManager.GetString("CreateMap_Alert_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除并创建 的本地化字符串。
        /// </summary>
        public static string CreateMap_Alert_Confirm {
            get {
                return ResourceManager.GetString("CreateMap_Alert_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已有地图，创建地图将会删除当前图，是否确认删除并创建新地图？ 的本地化字符串。
        /// </summary>
        public static string CreateMap_Alert_ConfirmDelete {
            get {
                return ResourceManager.GetString("CreateMap_Alert_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认并创建 的本地化字符串。
        /// </summary>
        public static string CreateMap_BT_ConfirmAndCreate {
            get {
                return ResourceManager.GetString("CreateMap_BT_ConfirmAndCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建成功！ 的本地化字符串。
        /// </summary>
        public static string CreateMap_Complete {
            get {
                return ResourceManager.GetString("CreateMap_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似           每排几列: 的本地化字符串。
        /// </summary>
        public static string CreateMap_LB_ColumnCount {
            get {
                return ResourceManager.GetString("CreateMap_LB_ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似          共几层:  的本地化字符串。
        /// </summary>
        public static string CreateMap_LB_LayerCount {
            get {
                return ResourceManager.GetString("CreateMap_LB_LayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似           地图名称： 的本地化字符串。
        /// </summary>
        public static string CreateMap_LB_MapName {
            get {
                return ResourceManager.GetString("CreateMap_LB_MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似         共几排: 的本地化字符串。
        /// </summary>
        public static string CreateMap_LB_RackCount {
            get {
                return ResourceManager.GetString("CreateMap_LB_RackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加存入任务 的本地化字符串。
        /// </summary>
        public static string EditMap_BT_AddStoreRequests {
            get {
                return ResourceManager.GetString("EditMap_BT_AddStoreRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加取出任务 的本地化字符串。
        /// </summary>
        public static string EditMap_BT_AddTakeOutRequests {
            get {
                return ResourceManager.GetString("EditMap_BT_AddTakeOutRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选择 的本地化字符串。
        /// </summary>
        public static string EditMap_CancelSelect {
            get {
                return ResourceManager.GetString("EditMap_CancelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建地图 的本地化字符串。
        /// </summary>
        public static string EditMap_CreateMapButton {
            get {
                return ResourceManager.GetString("EditMap_CreateMapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中区域的货物 的本地化字符串。
        /// </summary>
        public static string EditMap_DeleteSelectedStorage {
            get {
                return ResourceManager.GetString("EditMap_DeleteSelectedStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑地图属性 的本地化字符串。
        /// </summary>
        public static string EditMap_ModifyMapInformation {
            get {
                return ResourceManager.GetString("EditMap_ModifyMapInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑选中栅格类型 的本地化字符串。
        /// </summary>
        public static string EditMap_ModifySelectedMapItemsButton {
            get {
                return ResourceManager.GetString("EditMap_ModifySelectedMapItemsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看编辑货位区域类型 的本地化字符串。
        /// </summary>
        public static string EditMap_ModifyStorageZonesButton {
            get {
                return ResourceManager.GetString("EditMap_ModifyStorageZonesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string EditMap_RefreshAllMap {
            get {
                return ResourceManager.GetString("EditMap_RefreshAllMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存地图 的本地化字符串。
        /// </summary>
        public static string EditMap_SaveMap {
            get {
                return ResourceManager.GetString("EditMap_SaveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存地图完毕！ 的本地化字符串。
        /// </summary>
        public static string EditMap_SaveMap_Msg_Complete {
            get {
                return ResourceManager.GetString("EditMap_SaveMap_Msg_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择栅格 的本地化字符串。
        /// </summary>
        public static string EditMap_SelectMapItems {
            get {
                return ResourceManager.GetString("EditMap_SelectMapItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层选择 的本地化字符串。
        /// </summary>
        public static string EditMap_SelectMapLayer {
            get {
                return ResourceManager.GetString("EditMap_SelectMapLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个区域类型 的本地化字符串。
        /// </summary>
        public static string EditSelectedStorageType_LB_select {
            get {
                return ResourceManager.GetString("EditSelectedStorageType_LB_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加或修改连接 的本地化字符串。
        /// </summary>
        public static string EditSpecialConnection_LB_AddOrModify {
            get {
                return ResourceManager.GetString("EditSpecialConnection_LB_AddOrModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string EditSpecialConnection_LB_Unit {
            get {
                return ResourceManager.GetString("EditSpecialConnection_LB_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑选中货位的区域类型 的本地化字符串。
        /// </summary>
        public static string EditStorage_BT_EditSelectedStorageZones {
            get {
                return ResourceManager.GetString("EditStorage_BT_EditSelectedStorageZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加货物到选中货位 的本地化字符串。
        /// </summary>
        public static string EditStorage_BT_Modify {
            get {
                return ResourceManager.GetString("EditStorage_BT_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加上述区域类型 的本地化字符串。
        /// </summary>
        public static string GoodsTypes_BT_Add {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中区域类型 的本地化字符串。
        /// </summary>
        public static string GoodsTypes_BT_Delete {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改选中区域类型为上述 的本地化字符串。
        /// </summary>
        public static string GoodsTypes_BT_Modify {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存此次所有修改 的本地化字符串。
        /// </summary>
        public static string GoodsTypes_BT_SaveAll {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有 的本地化字符串。
        /// </summary>
        public static string GoodsTypes_LST_All {
            get {
                return ResourceManager.GetString("GoodsTypes_LST_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存完毕！ 的本地化字符串。
        /// </summary>
        public static string GoodsTypes_Msg_SaveComplete {
            get {
                return ResourceManager.GetString("GoodsTypes_Msg_SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子穿梭车属性 的本地化字符串。
        /// </summary>
        public static string MapInformation_GB_ChildShuttles {
            get {
                return ResourceManager.GetString("MapInformation_GB_ChildShuttles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提升机属性 的本地化字符串。
        /// </summary>
        public static string MapInformation_GB_Lifter {
            get {
                return ResourceManager.GetString("MapInformation_GB_Lifter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栅格间距 的本地化字符串。
        /// </summary>
        public static string MapInformation_GB_MapGapLength {
            get {
                return ResourceManager.GetString("MapInformation_GB_MapGapLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 母穿梭车属性 的本地化字符串。
        /// </summary>
        public static string MapInformation_GB_ParentShuttles {
            get {
                return ResourceManager.GetString("MapInformation_GB_ParentShuttles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速度： 的本地化字符串。
        /// </summary>
        public static string MapInformation_LB_Acceleration {
            get {
                return ResourceManager.GetString("MapInformation_LB_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减速度： 的本地化字符串。
        /// </summary>
        public static string MapInformation_LB_Deceleration {
            get {
                return ResourceManager.GetString("MapInformation_LB_Deceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列方向距离^： 的本地化字符串。
        /// </summary>
        public static string MapInformation_LB_GridColumnGap {
            get {
                return ResourceManager.GetString("MapInformation_LB_GridColumnGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层间距： 的本地化字符串。
        /// </summary>
        public static string MapInformation_LB_GridLayerGap {
            get {
                return ResourceManager.GetString("MapInformation_LB_GridLayerGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排方向间距&gt;： 的本地化字符串。
        /// </summary>
        public static string MapInformation_LB_GridRackGap {
            get {
                return ResourceManager.GetString("MapInformation_LB_GridRackGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高速度： 的本地化字符串。
        /// </summary>
        public static string MapInformation_LB_MaxSpeed {
            get {
                return ResourceManager.GetString("MapInformation_LB_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库点 的本地化字符串。
        /// </summary>
        public static string MapItems_Input {
            get {
                return ResourceManager.GetString("MapItems_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库点 的本地化字符串。
        /// </summary>
        public static string Mapitems_OutPut {
            get {
                return ResourceManager.GetString("Mapitems_OutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string MapItems_PleaseSelect {
            get {
                return ResourceManager.GetString("MapItems_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 母车轨道 的本地化字符串。
        /// </summary>
        public static string MapItems_Railway {
            get {
                return ResourceManager.GetString("MapItems_Railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货位 的本地化字符串。
        /// </summary>
        public static string MapItems_Storage {
            get {
                return ResourceManager.GetString("MapItems_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无属性，不计入地图 的本地化字符串。
        /// </summary>
        public static string MapItems_Unavalible {
            get {
                return ResourceManager.GetString("MapItems_Unavalible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手工入库一托货物 的本地化字符串。
        /// </summary>
        public static string Menu_AddOneUnitGoodsByHand {
            get {
                return ResourceManager.GetString("Menu_AddOneUnitGoodsByHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加分区 的本地化字符串。
        /// </summary>
        public static string Menu_AddZones {
            get {
                return ResourceManager.GetString("Menu_AddZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理连接 的本地化字符串。
        /// </summary>
        public static string Menu_ConnectionManagement {
            get {
                return ResourceManager.GetString("Menu_ConnectionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接两个栅格 的本地化字符串。
        /// </summary>
        public static string Menu_ConnectTwoGrids {
            get {
                return ResourceManager.GetString("Menu_ConnectTwoGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除连接 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteSpecialConnection {
            get {
                return ResourceManager.GetString("Menu_DeleteSpecialConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栅格编辑 的本地化字符串。
        /// </summary>
        public static string Menu_Grid {
            get {
                return ResourceManager.GetString("Menu_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据当前地图设置生成空白货道 的本地化字符串。
        /// </summary>
        public static string Menu_InitializeBlankCargoways {
            get {
                return ResourceManager.GetString("Menu_InitializeBlankCargoways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装载货道 的本地化字符串。
        /// </summary>
        public static string Menu_LoadCargoways {
            get {
                return ResourceManager.GetString("Menu_LoadCargoways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图 的本地化字符串。
        /// </summary>
        public static string Menu_Map {
            get {
                return ResourceManager.GetString("Menu_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记货道 的本地化字符串。
        /// </summary>
        public static string Menu_MarkCargoway {
            get {
                return ResourceManager.GetString("Menu_MarkCargoway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 算法移库一托货物 的本地化字符串。
        /// </summary>
        public static string Menu_MoveOneUnitGoodsByAlg {
            get {
                return ResourceManager.GetString("Menu_MoveOneUnitGoodsByAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手工移库一托货物 的本地化字符串。
        /// </summary>
        public static string Menu_MoveOneUnitGoodsByHand {
            get {
                return ResourceManager.GetString("Menu_MoveOneUnitGoodsByHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手工出库一托货物 的本地化字符串。
        /// </summary>
        public static string Menu_RetrieveOneUnitGoodsByHand {
            get {
                return ResourceManager.GetString("Menu_RetrieveOneUnitGoodsByHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置货道为通道 的本地化字符串。
        /// </summary>
        public static string Menu_SetCargowayAsSR {
            get {
                return ResourceManager.GetString("Menu_SetCargowayAsSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置整列为轨道 的本地化字符串。
        /// </summary>
        public static string Menu_SetWholeColumnAsRail {
            get {
                return ResourceManager.GetString("Menu_SetWholeColumnAsRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置分区 的本地化字符串。
        /// </summary>
        public static string Menu_SetZones {
            get {
                return ResourceManager.GetString("Menu_SetZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟出库 的本地化字符串。
        /// </summary>
        public static string Menu_SimulateRetrieve {
            get {
                return ResourceManager.GetString("Menu_SimulateRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟入库 的本地化字符串。
        /// </summary>
        public static string Menu_SimulateStore {
            get {
                return ResourceManager.GetString("Menu_SimulateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货位编辑 的本地化字符串。
        /// </summary>
        public static string Menu_Storage {
            get {
                return ResourceManager.GetString("Menu_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        public static string Menu_Task {
            get {
                return ResourceManager.GetString("Menu_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栅格管理 的本地化字符串。
        /// </summary>
        public static string Menu_Title_GridManagement {
            get {
                return ResourceManager.GetString("Menu_Title_GridManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库位管理 的本地化字符串。
        /// </summary>
        public static string Menu_Title_StorageManagement {
            get {
                return ResourceManager.GetString("Menu_Title_StorageManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分区管理 的本地化字符串。
        /// </summary>
        public static string Menu_Title_ZoneManagement {
            get {
                return ResourceManager.GetString("Menu_Title_ZoneManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理分区 的本地化字符串。
        /// </summary>
        public static string Menu_ZoneManagement {
            get {
                return ResourceManager.GetString("Menu_ZoneManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 若放弃编辑则栅格类型不会被改变，是否确认放弃此次编辑？ 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_AskForQuit {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_AskForQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未确认此次修改，是否确认？ 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_AskForSave {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_AskForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;&gt;添加&gt;&gt; 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_BT_AddGT {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_BT_AddGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;&lt;删除&lt;&lt; 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_BT_DeleteGT {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_BT_DeleteGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有层的相同位置应用相同配置 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_CB_ApplyToAllLayer {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_CB_ApplyToAllLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑成功！ 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_GoodsTypes_Complete {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_GoodsTypes_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货位允许类别 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_LB_AvailableTypes {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_LB_AvailableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可选货位类别 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_LB_GoodsTypesList {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_LB_GoodsTypesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择栅格类别 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_LB_GridType {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_LB_GridType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前选中位置包含货物，编辑后将会将货物信息删除！ 的本地化字符串。
        /// </summary>
        public static string ModifySelectedMapItem_Msg_AlertForGoodsInfo {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_Msg_AlertForGoodsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物批次： 的本地化字符串。
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodBatch {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物数量： 的本地化字符串。
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodCount {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物类型： 的本地化字符串。
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodModel {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货物名称： 的本地化字符串。
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodName {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认取出： 的本地化字符串。
        /// </summary>
        public static string ModifySelectedStorage_MB_ConfirmTakeOut {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_MB_ConfirmTakeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
