//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoWays
    {
        public int Id { get; set; }
        public int LeftRailColumn { get; set; }
        public int RightRailColumn { get; set; }
        public bool LeftIsRail { get; set; }
        public bool RightIsRail { get; set; }
        public string CargoWayNumber { get; set; }
        public int ZoneAt { get; set; }
        public int LayerAt { get; set; }
        public int ColAt { get; set; }
    }
}
