//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoWaysLock
    {
        public int Id { get; set; }
        public int LockStart { get; set; }
        public int LockEnd { get; set; }
        public int InPointMapItemId { get; set; }
        public int CargoWayId { get; set; }
        public int RailColumn { get; set; }
        public int LayerAt { get; set; }
        public int RackAt { get; set; }
    }
}
