//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevEntities : DbContext
    {
        public DevEntities()
            : base("name=DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MapDictionary> MapDictionary { get; set; }
        public virtual DbSet<Zone> Zone { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<MapItems> MapItems { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<SpecialConnection> SpecialConnection { get; set; }
        public virtual DbSet<CargoWaysLock> CargoWaysLock { get; set; }
        public virtual DbSet<CargoWays> CargoWays { get; set; }
        public virtual DbSet<Rails> Rails { get; set; }
    }
}
