//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int Id { get; set; }
        public string BarCode { get; set; }
        public int MapItemsId { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Batch { get; set; }
        public int Count { get; set; }
        public string ProductId { get; set; }
        public int CargoWayLockId { get; set; }
    }
}
