//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapItems
    {
        public int Id { get; set; }
        public int MapItemLayer { get; set; }
        public int MapItemRack { get; set; }
        public int MapItemColumn { get; set; }
        public int ZoneId { get; set; }
        public int TypeId { get; set; }
        public int CargowayId { get; set; }
        public int Status { get; set; }
    }
}
