//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localiztion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localiztion.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法货物数量，当前货物数量应在以下范围：.
        /// </summary>
        public static string AddTakeOutRequest_IllegalCount_MSG {
            get {
                return ResourceManager.GetString("AddTakeOutRequest_IllegalCount_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string BT_Confirm {
            get {
                return ResourceManager.GetString("BT_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重设.
        /// </summary>
        public static string BT_Rest {
            get {
                return ResourceManager.GetString("BT_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string BT_Save {
            get {
                return ResourceManager.GetString("BT_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认并创建.
        /// </summary>
        public static string CreateMap_BT_ConfirmAndCreate {
            get {
                return ResourceManager.GetString("CreateMap_BT_ConfirmAndCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建成功！.
        /// </summary>
        public static string CreateMap_Complete {
            get {
                return ResourceManager.GetString("CreateMap_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           每排几列:.
        /// </summary>
        public static string CreateMap_LB_ColumnCount {
            get {
                return ResourceManager.GetString("CreateMap_LB_ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          共几层: .
        /// </summary>
        public static string CreateMap_LB_LayerCount {
            get {
                return ResourceManager.GetString("CreateMap_LB_LayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         共几排:.
        /// </summary>
        public static string CreateMap_LB_RackCount {
            get {
                return ResourceManager.GetString("CreateMap_LB_RackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加存入任务.
        /// </summary>
        public static string EditMap_BT_AddStoreRequests {
            get {
                return ResourceManager.GetString("EditMap_BT_AddStoreRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加取出任务.
        /// </summary>
        public static string EditMap_BT_AddTakeOutRequests {
            get {
                return ResourceManager.GetString("EditMap_BT_AddTakeOutRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消选择.
        /// </summary>
        public static string EditMap_CancelSelect {
            get {
                return ResourceManager.GetString("EditMap_CancelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建地图.
        /// </summary>
        public static string EditMap_CreateMapButton {
            get {
                return ResourceManager.GetString("EditMap_CreateMapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看编辑货物类型.
        /// </summary>
        public static string EditMap_ModifyGoodsTypesButton {
            get {
                return ResourceManager.GetString("EditMap_ModifyGoodsTypesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑地图属性.
        /// </summary>
        public static string EditMap_ModifyMapInformation {
            get {
                return ResourceManager.GetString("EditMap_ModifyMapInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑选中栅格.
        /// </summary>
        public static string EditMap_ModifySelectedMapItemsButton {
            get {
                return ResourceManager.GetString("EditMap_ModifySelectedMapItemsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存地图.
        /// </summary>
        public static string EditMap_SaveMap {
            get {
                return ResourceManager.GetString("EditMap_SaveMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存地图完毕！.
        /// </summary>
        public static string EditMap_SaveMap_Msg_Complete {
            get {
                return ResourceManager.GetString("EditMap_SaveMap_Msg_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择栅格.
        /// </summary>
        public static string EditMap_SelectMapItems {
            get {
                return ResourceManager.GetString("EditMap_SelectMapItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑选中货位.
        /// </summary>
        public static string EditStorage_BT_Modify {
            get {
                return ResourceManager.GetString("EditStorage_BT_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加上述货物类型.
        /// </summary>
        public static string GoodsTypes_BT_Add {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除选中货物类型.
        /// </summary>
        public static string GoodsTypes_BT_Delete {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改选中货物类型为上述.
        /// </summary>
        public static string GoodsTypes_BT_Modify {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存此次所有修改.
        /// </summary>
        public static string GoodsTypes_BT_SaveAll {
            get {
                return ResourceManager.GetString("GoodsTypes_BT_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有.
        /// </summary>
        public static string GoodsTypes_LST_All {
            get {
                return ResourceManager.GetString("GoodsTypes_LST_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存完毕！.
        /// </summary>
        public static string GoodsTypes_Msg_SaveComplete {
            get {
                return ResourceManager.GetString("GoodsTypes_Msg_SaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子穿梭车属性.
        /// </summary>
        public static string MapInformation_GB_ChildShuttles {
            get {
                return ResourceManager.GetString("MapInformation_GB_ChildShuttles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提升机属性.
        /// </summary>
        public static string MapInformation_GB_Lifter {
            get {
                return ResourceManager.GetString("MapInformation_GB_Lifter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 栅格间距.
        /// </summary>
        public static string MapInformation_GB_MapGapLength {
            get {
                return ResourceManager.GetString("MapInformation_GB_MapGapLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 母穿梭车属性.
        /// </summary>
        public static string MapInformation_GB_ParentShuttles {
            get {
                return ResourceManager.GetString("MapInformation_GB_ParentShuttles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加速度：.
        /// </summary>
        public static string MapInformation_LB_Acceleration {
            get {
                return ResourceManager.GetString("MapInformation_LB_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 减速度：.
        /// </summary>
        public static string MapInformation_LB_Deceleration {
            get {
                return ResourceManager.GetString("MapInformation_LB_Deceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列方向距离^：.
        /// </summary>
        public static string MapInformation_LB_GridColumnGap {
            get {
                return ResourceManager.GetString("MapInformation_LB_GridColumnGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层间距：.
        /// </summary>
        public static string MapInformation_LB_GridLayerGap {
            get {
                return ResourceManager.GetString("MapInformation_LB_GridLayerGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排方向间距&gt;：.
        /// </summary>
        public static string MapInformation_LB_GridRackGap {
            get {
                return ResourceManager.GetString("MapInformation_LB_GridRackGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高速度：.
        /// </summary>
        public static string MapInformation_LB_MaxSpeed {
            get {
                return ResourceManager.GetString("MapInformation_LB_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入库点.
        /// </summary>
        public static string MapItems_Input {
            get {
                return ResourceManager.GetString("MapItems_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出库点.
        /// </summary>
        public static string Mapitems_OutPut {
            get {
                return ResourceManager.GetString("Mapitems_OutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择.
        /// </summary>
        public static string MapItems_PleaseSelect {
            get {
                return ResourceManager.GetString("MapItems_PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 母车轨道.
        /// </summary>
        public static string MapItems_Railway {
            get {
                return ResourceManager.GetString("MapItems_Railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货位.
        /// </summary>
        public static string MapItems_Storage {
            get {
                return ResourceManager.GetString("MapItems_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无属性，不计入地图.
        /// </summary>
        public static string MapItems_Unavalible {
            get {
                return ResourceManager.GetString("MapItems_Unavalible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若放弃编辑则栅格类型不会被改变，是否确认放弃此次编辑？.
        /// </summary>
        public static string ModifySelectedMapItem_AskForQuit {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_AskForQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未确认此次修改，是否确认？.
        /// </summary>
        public static string ModifySelectedMapItem_AskForSave {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_AskForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;添加&gt;&gt;.
        /// </summary>
        public static string ModifySelectedMapItem_BT_AddGT {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_BT_AddGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;删除&lt;&lt;.
        /// </summary>
        public static string ModifySelectedMapItem_BT_DeleteGT {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_BT_DeleteGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有层的相同位置应用相同配置.
        /// </summary>
        public static string ModifySelectedMapItem_CB_ApplyToAllLayer {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_CB_ApplyToAllLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑成功！.
        /// </summary>
        public static string ModifySelectedMapItem_GoodsTypes_Complete {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_GoodsTypes_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货位允许类别.
        /// </summary>
        public static string ModifySelectedMapItem_LB_AvailableTypes {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_LB_AvailableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可选货位类别.
        /// </summary>
        public static string ModifySelectedMapItem_LB_GoodsTypesList {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_LB_GoodsTypesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择栅格类别.
        /// </summary>
        public static string ModifySelectedMapItem_LB_GridType {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_LB_GridType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前选中位置包含货物，编辑后将会将货物信息删除！.
        /// </summary>
        public static string ModifySelectedMapItem_Msg_AlertForGoodsInfo {
            get {
                return ResourceManager.GetString("ModifySelectedMapItem_Msg_AlertForGoodsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货物编号：.
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodCode {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货物数量：.
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodCount {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货物名称：.
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodName {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货物规格：.
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodSpecification {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可选货物类别.
        /// </summary>
        public static string ModifySelectedStorage_LB_GoodTypes {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_GoodTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货物订单编号：.
        /// </summary>
        public static string ModifySelectedStorage_LB_OrderCode {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_OrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货物所属类别.
        /// </summary>
        public static string ModifySelectedStorage_LB_SetGoodTypes {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_LB_SetGoodTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认取出：.
        /// </summary>
        public static string ModifySelectedStorage_MB_ConfirmTakeOut {
            get {
                return ResourceManager.GetString("ModifySelectedStorage_MB_ConfirmTakeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
